[build]
  functions = "netlify/functions"

[[headers]]
  for = "/downloads/*"
  [headers.values]
    X-Content-Type-Options = "nosniff"
    Cache-Control = "no-store"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
